services:
  depositor:
    image: ghcr.io/swissopenem/depositor:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    environment:
      - PORT=8080
      - ALLOW_ORIGINS=${SCICAT_FRONTEND_URL}
    volumes:
      - ./data/conversions.csv:/app/data/conversions.csv
      - ./data/mmcif_pdbx_v50.dic:/app/data/mmcif_pdbx_v50.dic